app/models/exercise.py
from .. import db

class Exercise(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    training_id = db.Column(db.Integer, db.ForeignKey('training.id', ondelete='CASCADE'))
    exerciseName = db.Column(db.String(100))
    muscleGroups = db.Column(db.String(100))
    numberOfTimes = db.Column(db.Integer)
    numberOfSets = db.Column(db.Integer)

app/models/training.py
from datetime import datetime

from ..models.exercise import Exercise
from .. import db

class Training(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    trainings = db.relationship(Exercise, backref='training')
    trainingName = db.Column(db.String(100))
    muscleGroups = db.Column(db.String(100))
    date = db.Column(db.DateTime, default=datetime.now())

app/models/user.py
from datetime import datetime

from ..models.training import Training
from .. import db, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User (db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    trainings = db.relationship(Training, backref='author')
    status = db.Column(db.String(50), default='user')
    avatar = db.Column(db.String(200))
    name = db.Column(db.String(100))
    login = db.Column(db.String(64))
    password = db.Column(db.String(200))
    date = db.Column(db.DateTime, default=datetime.now())

app/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, FileField, PasswordField, StringField, SubmitField, ValidationError
from flask_wtf.file import FileAllowed
from wtforms.validators import DataRequired, Length, Email, EqualTo

from .models.user import User

class RegistrationForm(FlaskForm):
    name = StringField('ФИО', validators=[DataRequired(),Length(min=2, max=100)])
    login = StringField('Логин', validators=[DataRequired(),Length(min=2, max=64)])
    password = PasswordField('Пароль', validators=[DataRequired(),Length(min=2, max=64)])
    confirm_password = PasswordField('Подтвердить пароль', validators=[DataRequired(),Length(min=2, max=64), EqualTo('password')])
    avatar = FileField('Загрузите фото', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Зарегистрироваться')
    
    def validate_login(self, login):
        user = User.query.filter_by(login=login.data).first()
        if user:
            raise ValidationError('Данный логин пользователя уже занят')
        
class LoginForm(FlaskForm):
    login = StringField('Логин', validators=[DataRequired(),Length(min=2, max=64)])
    password = PasswordField('Пароль', validators=[DataRequired(),Length(min=2, max=64)])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_assets import Environment
from app.config import Config


db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
login_manager = LoginManager()
assets = Environment()

def create_app(config_app=Config):
    app = Flask(__name__)
    
    config = Config()
    
    from .routes.user import user
    app.register_blueprint(user)
    
    from .routes.training import training
    app.register_blueprint(training)
    
    app.config.from_object(config_app)
    
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    assets.init_app(app)
    
    login_manager.login_view = 'user.login'
    login_manager.login_message = 'Вы не можете получить доступ к данной странице'
    login_manager.login_message_category = 'info'
    
    with app.app_context():
        db.create_all()
    
    return app

app/routes.py
from flask import Blueprint
from app import db
from app.models.user import User

user = Blueprint('user', __name__)

@user.route('/user/<name>')
def create_user(name):
    user = User()
    user.id = 1
    user.name = name
    db.session.add(user)
    db.session.commit()
    return "User Created!"

app/routes/training.py
from flask import Blueprint, redirect, render_template, request
from flask_login import current_user, login_required
from .. import db
from ..models.training import Training

training = Blueprint('training', __name__)

@training.route("/", methods=['GET'])
def show_all():
    trainings = Training.query.all()
    return render_template('training/popular.html', trainings=trainings)

@training.route('/training/create', methods=['POST','GET'])
@login_required
def create():
    if request.method == 'POST':
        trainingName = request.form.get('trainingName')
        muscleGroups = request.form.get('muscleGroups')
        
        training = Training(user=current_user.id,trainingName=trainingName, muscleGroups=muscleGroups)
        try:
            db.session.add(training)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
        return redirect('/')
    else:
        return render_template('training/create.html')
    
@training.route('/training/<int:id>/update', methods=['POST', 'GET'])
@login_required
def update(id):
    training = Training.query.get(id)
    if request.method == 'POST':
        training.trainingName = request.form.get('trainingName')
        training.muscleGroups = request.form.get('muscleGroups')
        
        try:
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
            
        return redirect('/')
    else:
        return render_template('training/update.html', training=training)
    
@training.route('/training/<int:id>/delete', methods=['GET'])
@login_required
def delete(id):
    training = Training.query.get(id)
    try:
        db.session.delete(training)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print(str(e))
        
    return redirect('/')

app/routes/user.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user, logout_user
from ..functions import save_picture
from ..forms import LoginForm, RegistrationForm
from .. import db, bcrypt
from ..models.user import User

user = Blueprint('user', __name__)

@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hased_password = bcrypt.generate_password_hash(password=form.password.data).decode('utf-8')
        avatar_file_name = save_picture(form.avatar.data)
        try:
            user = User(name=form.name.data, login=form.login.data, avatar=avatar_file_name, password=hased_password)
            db.session.add(user)
            db.session.commit()
            flash(f"Регистрация прошла успешно", "success")
            return redirect(url_for('user.login'))
        except Exception as e:
            flash(f"При регистрации произошла ошибка", "danger")
    return render_template('user/registry.html', form=form)

@user.route('/user/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('training.show_all'))
        else:
            flash("Ошибка входа. Проверьте логин или пароль", "danger")
    return render_template('user/login.html', form=form)

@user.route('/user/logout', methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('training.show_all'))

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <title>
    {% block title %}
    {% endblock title %}
    </title>
</head>
<body>
    <header class="header">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <img class='header_img' src="{{ url_for('static', filename='img/man.png') }}" alt="bodybuilder">
            </a>
  
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="/" class="nav-link px-2 text-secondary">Home</a></li>
              {% if current_user.is_authenticated and current_user.status == 'admin'%}
                <li><a href="{{ url_for('training.create') }}" class="nav-link px-2 text-white">Create training</a></li>
              {% endif %}
            </ul>
            
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
              <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
            </form>
    
            <div class="text-end">
              
              {% if current_user.is_authenticated%}
              <span>Добро пожаловать, {{ current_user.login }}</span>
              <a href="{{ url_for('user.logout') }}"><button type="button" class="btn btn-warning">Logout</button></a>
              {% else %}
              <a href="{{ url_for('user.login') }}"><button type="button" class="btn btn-warning">Login</button></a>
              <a href="{{ url_for('user.register') }}"><button type="button" class="btn btn-outline-light me-2">Sign-up</button></a>
              {% endif %}
            </div>
          </div>
    </header>
    <div class="page">
        <main class="content">
          {% include 'main/flash.html' %}
          <h1>
            {{ self.title() }}
          </h1>
          <div>
            {% block content %}
            
            {% endblock content %}
          </div>
        </main>
    
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <img class='header_img' src="{{ url_for('static', filename='img/man.png') }}" alt="bodybuilder">
              </a>
              <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
            </div>
        
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
              <li class="ms-3"><a class="text-body-secondary" href="#"><img class='header_img' src="{{ url_for('static', filename='img/github.png') }}" alt="github"></a></li>
              <li class="ms-3"><a class="text-body-secondary" href="#"><img class='header_img' src="{{ url_for('static', filename='img/leetcode.png') }}" alt="leetcode"></a></li>
              <li class="ms-3"><a class="text-body-secondary" href="#"><img class='header_img' src="{{ url_for('static', filename='img/telegram.png') }}" alt="telegram"></a></li>
            </ul>
          </footer>
    </div>
</body>
</html>

app/templates/main/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/training/create.html
{% extends 'main/base.html' %}

{% block title %}
    Создание Тренировки
{% endblock title %}

{% block content %}
    <form method="post" class="form-control">
        <input name="trainingName" type="text" placeholder="Название Тренировки" class="form-control">
        <input name="muscleGroups" type="text" placeholder="Название Тренировки" class="form-control">
        <input value="Добавить" type="submit" class="btn btn-success">
    </form> 
{% endblock content %}

app/templates/training/popular.html
{% extends 'main/base.html' %}

{% block title %}
    Популярные тренировки
{% endblock title %}

{% block content %}
    {% for training in trainings%}
        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading fw-normal lh-1">{{ training.trainingName }}</h2>
                <h3 class="featurette-heading fw-normal lh-1">Группы мышц: {{ training.muscleGroups }}</h3>
                
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('training.update', id=training.id) }}" class="btn btn-sm btn-secondary"><i class="fa-sharp fa-solid fa-pen-to-square"></i></a>
                    <a href="{{ url_for('training.delete', id=training.id) }}" class="btn btn-sm btn-danger"><i class="fa-solid fa-trash"></i></a>
                {% endif %}
            </div>
            <div class="col-md-5">
                <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="200" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

app/templates/training/update.html
{% extends 'main/base.html' %}

{% block title %}
    Редактировать Тренировку
{% endblock title %}

{% block content %}
    <form method="post" class="form-control">
        <input name="trainingName" type="text" placeholder="Название Тренировки" class="form-control" value="{{training.trainingName}}">
        <input name="muscleGroups" type="text" placeholder="Название Тренировки" class="form-control" value="{{training.muscleGroups}}">
        <input value="Обновить" type="submit" class="btn btn-success" >
    </form> 
{% endblock content %}

app/templates/user/login.html
{% extends 'main/base.html' %}

{% block title %}
    Авторизация
{% endblock title %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.login(class="form-control", placeholder="Логин") }}
        {{ form.password(class="form-control", placeholder="Пароль") }}
        <div class="flex flex-row">
            {{ form.remember.label}}{{ form.remember(class="form-check")}}
        </div>
        {{ form.submit(class="btn btn-success") }}
    </form> 
{% endblock content %}

app/templates/user/registry.html
{% extends 'main/base.html' %}

{% block title %}
    Регистрация
{% endblock title %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.name(class="form-control", placeholder="ФИО") }}
        {{ form.login(class="form-control", placeholder="Логин") }}
        {% if form.login.errors %}
            <div class="invalid-feedback" style="display: block!important;">
                
                {% for error in form.login.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
                    
            </div>
        {% endif %}
        {{ form.avatar(class="form-control") }}
        {{ form.password(class="form-control", placeholder="Пароль") }}
        {{ form.confirm_password(class="form-control", placeholder="Подтвердите пароль") }}
        {{ form.submit(class="btn btn-success") }}
    </form> 
{% endblock content %}